-- Crear tabla de tipos de identificación si no existe
CREATE TABLE identification_types
(
    identification_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(200),
    created_at TIMESTAMP(3) NOT NULL
        CONSTRAINT df_identification_types_created_at
        DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

-- Crear tabla Clients (solo si no existe) y referenciar IdentificationTypes
CREATE TABLE clients
(
    client_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number VARCHAR(20) NOT NULL UNIQUE,
    identification_type_id INTEGER NOT NULL CONSTRAINT df_clients_identification_type_id DEFAULT 1,
    identification_number VARCHAR(100),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    address_line1 VARCHAR(200),
    address_line2 VARCHAR(200),
    city VARCHAR(100),
    state_province VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    date_of_birth DATE,
    is_active BOOLEAN NOT NULL CONSTRAINT df_clients_is_active DEFAULT TRUE,
    created_at TIMESTAMP(3) NOT NULL CONSTRAINT df_clients_created_at DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    modified_at TIMESTAMP(3),
    row_ver BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_clients_identification_type FOREIGN KEY (identification_type_id) REFERENCES identification_types (identification_type_id)
);

-- Creates or alters a view that exposes clients with their identification type info
CREATE OR REPLACE VIEW vw_clients_with_identification AS
SELECT
    c.client_id,
    c.customer_number,
    c.identification_type_id,
    it.code AS identification_type_code,
    it.description AS identification_type_description,
    c.identification_number,
    c.first_name,
    c.last_name,
    c.email,
    c.phone,
    c.address_line1,
    c.address_line2,
    c.city,
    c.state_province,
    c.postal_code,
    c.country,
    c.date_of_birth,
    c.is_active,
    c.created_at,
    c.modified_at
FROM clients AS c
LEFT JOIN identification_types AS it
    ON c.identification_type_id = it.identification_type_id;
