-- Crear tabla de tipos de identificación si no existe
CREATE TABLE identification_types
(
    identification_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(200),
    created_at TIMESTAMP(3) NOT NULL
        CONSTRAINT df_identification_types_created_at
        DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

-- Crear tabla Clients (solo si no existe) y referenciar IdentificationTypes
CREATE TABLE clients
(
    client_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number VARCHAR(20) NOT NULL UNIQUE,
    identification_type_id INTEGER NOT NULL CONSTRAINT df_clients_identification_type_id DEFAULT 1,
    identification_number VARCHAR(100),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    address_line1 VARCHAR(200),
    address_line2 VARCHAR(200),
    city VARCHAR(100),
    state_province VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    date_of_birth DATE,
    is_active BOOLEAN NOT NULL CONSTRAINT df_clients_is_active DEFAULT TRUE,
    created_at TIMESTAMP(3) NOT NULL CONSTRAINT df_clients_created_at DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    modified_at TIMESTAMP(3),
    row_ver BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_clients_identification_type FOREIGN KEY (identification_type_id) REFERENCES identification_types (identification_type_id)
);

-- Creates or alters a view that exposes clients with their identification type info
CREATE OR REPLACE VIEW vw_clients_with_identification AS
SELECT
    c.client_id,
    c.customer_number,
    c.identification_type_id,
    it.code AS identification_type_code,
    it.description AS identification_type_description,
    c.identification_number,
    c.first_name,
    c.last_name,
    c.email,
    c.phone,
    c.address_line1,
    c.address_line2,
    c.city,
    c.state_province,
    c.postal_code,
    c.country,
    c.date_of_birth,
    c.is_active,
    c.created_at,
    c.modified_at
FROM clients AS c
LEFT JOIN identification_types AS it
    ON c.identification_type_id = it.identification_type_id;

-- Create or alter a stored procedure that inserts a client and returns the inserted row
CREATE OR REPLACE FUNCTION usp_insert_client(
    p_customer_number          VARCHAR(20),
    p_identification_type_id   INTEGER,
    p_first_name               VARCHAR(100),
    p_last_name                VARCHAR(100),

    p_identification_number    VARCHAR(100) DEFAULT NULL,
    p_email                    VARCHAR(255) DEFAULT NULL,
    p_phone                    VARCHAR(50) DEFAULT NULL,
    p_address_line1            VARCHAR(200) DEFAULT NULL,
    p_address_line2            VARCHAR(200) DEFAULT NULL,
    p_city                     VARCHAR(100) DEFAULT NULL,
    p_state_province           VARCHAR(100) DEFAULT NULL,
    p_postal_code              VARCHAR(20) DEFAULT NULL,
    p_country                  VARCHAR(100) DEFAULT NULL,
    p_date_of_birth            DATE DEFAULT NULL,
    p_is_active                BOOLEAN DEFAULT TRUE
)
RETURNS SETOF clients
LANGUAGE plpgsql
AS $$
BEGIN

    -- Validar IdentificationTypeID
    IF NOT EXISTS (
        SELECT 1
        FROM identification_types
        WHERE identification_type_id = p_identification_type_id
    ) THEN
        RAISE EXCEPTION 'IdentificationTypeID does not exist.'
            USING ERRCODE = '23503';
    END IF;

    -- Insertar y devolver el registro
    RETURN QUERY
    INSERT INTO clients
    (
        customer_number,
        identification_type_id,
        identification_number,
        first_name,
        last_name,
        email,
        phone,
        address_line1,
        address_line2,
        city,
        state_province,
        postal_code,
        country,
        date_of_birth,
        is_active
    )
    VALUES
    (
        p_customer_number,
        p_identification_type_id,
        p_identification_number,
        p_first_name,
        p_last_name,
        p_email,
        p_phone,
        p_address_line1,
        p_address_line2,
        p_city,
        p_state_province,
        p_postal_code,
        p_country,
        p_date_of_birth,
        p_is_active
    )
    RETURNING *;

END;
$$;
